In [5]:
# 1 -
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print("Utilizando For:")
for x in arr:
    for y in x:
        for z in y:
            print(z)
            
print('-'*32)
print("Utilizando Numpy <nditer>:")
for i in np.nditer(arr):
    print(i)
    
print('-'*32)

# Em questão de velocidade de execução, ambas desempenham de igual forma, porém a função própria do Numpy é muito superior o no quesito de legibilidade por fazer a mesma coisa que o for de 3 dimensões em apenas um for.



Utilizando For:
1
2
3
4
5
6
7
8
9
10
11
12
--------------------------------
Utilizando Numpy <nditer>:
1
2
3
4
5
6
7
8
9
10
11
12
--------------------------------


In [71]:
# 2

# Array usado pra não ficar tendo que digitar toda hora euahuea
# comidas_favoritas = ["maçã", "uva", "morango", "melancia", "acelga"]

comidas_favoritas = []
vogais = ['a', 'e', 'i', 'o', 'u']

count = int(input("Digite o número de comidas favoritas:"))

for i in range(count):
    comidas_favoritas.append(input(f"Digite {i+1}º sua comida favorita:"))

arr_comidas = np.array(comidas_favoritas)

print("Array Original: ", arr_comidas)

index = 0
indexes = []
# Decidi percorrer o array coletando os indexes de onde encontrei palavras iniciadas em vogais. Sei que provavelmente daria pra fazer isso em uma linha usando comprehension, mas tô pegando o jeito.
for x in arr_comidas:
    if x[0] in vogais:
        indexes.append(index)
    index += 1
# Ao fim passo as modificações para um array criado, removendo os indexes que encontrei ao percorrer o original
arr_modificado = np.delete(arr_comidas, indexes)
print("Array Modificado <np.delete>: ", arr_modificado)

# A idéia veio dps de mta pesquisa e veio daqui: https://www.delftstack.com/pt/howto/numpy/numpy-remove-element-from-array/

['uva' 'maçã' 'banana']
Array Modificado <np.delete>:  ['maçã' 'banana']


In [82]:
# 3 - Shape!

a = np.array(2)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print("Dimensão <a>", np.shape(a))
print("O array <a> contém apenas um elemento.")
print("Dimensão <b>", np.shape(b))
print("Dimensão <c>", np.shape(c))
print("Dimensão <d>", np.shape(d))

Dimensão <a> ()
O array <a> contém apenas um elemento.
Dimensão <b> (5,)
Dimensão <c> (2, 3)
Dimensão <d> (2, 2, 3)


In [89]:
# 4 - Reshape!!!

arr = [1, 2, 3, 4, 'Amelia', 'Bruna', 'Carolina', 'Débora', True, False, False, True]

array_4 = np.array(arr)

array_4 = array_4.reshape(4, 3)

print("4x3 <reshape>: ")
print(array_4)
print('-'*32)

array_4 = array_4.reshape(3, 4)

print("3x4 <reshape>: ")
print(array_4)
print('-'*32)

4x3 <reshape>: 
[['1' '2' '3']
 ['4' 'Amelia' 'Bruna']
 ['Carolina' 'Débora' 'True']
 ['False' 'False' 'True']]
--------------------------------
3x4 <reshape>: 
[['1' '2' '3' '4']
 ['Amelia' 'Bruna' 'Carolina' 'Débora']
 ['True' 'False' 'False' 'True']]
--------------------------------


In [94]:
# 5
arr = range(27)

arr_5 = np.array(arr)

arr_5 = arr_5.reshape(3, 3, 3)

print("3x3x3 <reshape>: ")
print(arr_5)
print('-'*32)

# Uma matriz de 3D é semelhante à uma matriz 3x3, porém com uma camada a mais, tornando-se um "cubo". A partir desta terceira camada é um pouco difícil pra nós entendermos, porém poderia ser interpretada como a "profundidade" de um cubo.


3x3x3 <reshape>: 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
--------------------------------


In [95]:
# 6 -

arr = [1, 2, 3, 4, 5, 6, 7, 8]

arr_6 = np.array(arr).reshape(3, 3, 3)

# Não funciona, basicamente pois não há elementos suficientes para preencher toda matriz. Nosso array possui apenas 8 elementos enquanto a matriz solicita o produto de todas as suas "arestas". Sendo assim, seriam necessários (no mínimo) 3x3x3 = 27 elementos.


ValueError: cannot reshape array of size 8 into shape (3,3,3)

In [97]:
# 7 - 

arr = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

arr_7 = np.array(arr)

print("Utilizando for encaixado:")
for x in arr_7:
    for y in x:
        for z in y:
            print(z)
print('-'*32)

print("Utilizando Numpy <nditer>:")
for i in np.nditer(arr_7):
    print(i)


Utilizando Numpy <nditer>:
1
2
3
4
5
6
7
8
--------------------------------
Utilizando Numpy <nditer>:
1
2
3
4
5
6
7
8


In [122]:
# 8 - 
arr = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

arr_8 = np.array(arr)
contx = 0
conty = 0
contz = 0


print("Utilizando for encaixado:")
for x in arr_7:
    for y in x:
        for z in y:
            print(f"({contx}, {conty}, {contz}) = {z}")
            contz += 1
        conty += 1
        contz = 0 # resetando o indice
    contx += 1
    conty = 0 # resetando o indice
    contz = 0 # resetando o indice
print('-'*32)
    
print("Utilizando Numpy <ndenumerate>:")
for index, j in np.ndenumerate(arr_8):
    print(index, j)
print('-'*32)
        
            
            



Utilizando for encaixado:
(0, 0, 0) = 1
(0, 0, 1) = 2
(0, 1, 0) = 3
(0, 1, 1) = 4
(1, 0, 0) = 5
(1, 0, 1) = 6
(1, 1, 0) = 7
(1, 1, 1) = 8
--------------------------------
Utilizando Numpy <ndenumerate>:
(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8
--------------------------------


In [114]:
# 9 -

arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])


arr_horizontal =  np.hstack((arr_1, arr_2))
print("Array resultante horizontal <hstack>: ")
print(arr_horizontal)
print('-'*21)


arr_vertical = np.vstack((arr_1, arr_2))
print("Array resultante vertical <vstack>: ")
print(arr_vertical)
print('-'*21)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [123]:
# 10 - 

frutas = ['banana', 'morango', 'uva', 'pitaia', 'abacate', 'abacaxi', 'acerola', 'jenipapo', 'kiwi']

vogais = ['a', 'e', 'i', 'o', 'u']

arr_frutas = np.array(frutas)
count = 0

for index, x in np.ndenumerate(arr_frutas):
    for y in x:
        if y in vogais:
            count += 1
    if count == 2:
        print(f"A palavra {x} no index {index} possui apenas duas vogais.")
    count = 0

A palavra uva no index (2,) possui apenas duas vogais.
A palavra kiwi no index (8,) possui apenas duas vogais.


In [133]:
# 11 -

arr = [[1, 2], [3, 4], [5, 6], [7, 8]]

arr_11 = np.array(arr)

print("Array Original")
print(arr_11)
print('-'*32)

arr_dividido = np.split(arr_11, 2)

print("Divisão de array <split>: ")
print(arr_dividido[0])
print(np.shape(arr_dividido[0]))
print('-'*32)

print("Divisão de array <split>: ")
print(arr_dividido[1])
print(np.shape(arr_dividido[1]))
print('-'*32)

arr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr_11 = np.array(arr)

print("Array Original")
print(arr_11)
print('-'*32)

arr_dividido = np.split(arr_11, 3, axis = 1)

print("Divisão de array - coluna 1 <split>: ")
print(arr_dividido[0])
print(np.shape(arr_dividido[0]))
print('-'*32)

print("Divisão de array - coluna 2 <split>: ")
print(arr_dividido[1])
print(np.shape(arr_dividido[1]))
print('-'*32)

print("Divisão de array - coluna 3 <split>: ")
print(arr_dividido[2])
print(np.shape(arr_dividido[2]))
print('-'*32)


Array Original
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
--------------------------------
Divisão de array <split>: 
[[1 2]
 [3 4]]
(2, 2)
--------------------------------
Divisão de array <split>: 
[[5 6]
 [7 8]]
(2, 2)
--------------------------------
Array Original
[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------------
Divisão de array - coluna 1 <split>: 
[[1]
 [4]
 [7]]
(3, 1)
--------------------------------
Divisão de array - coluna 2 <split>: 
[[2]
 [5]
 [8]]
(3, 1)
--------------------------------
Divisão de array - coluna 3 <split>: 
[[3]
 [6]
 [9]]
(3, 1)
--------------------------------


In [156]:
arr = ['Amélia', 13, 'F', 'peixes', 1.51, 9, 7, True, 'Bruno', 14, 'O', 'leão', 1.60, 4, 10, False, 'João', 14, 'M', 'escorpião', 1.58, 8, 9, True, 'Jordana', 13, 'F', 'escorpião', 1.72, 9, 9, False]

arr_12 = np.array(arr)
print(arr_12)


['Amélia' '13' 'F' 'peixes' '1.51' '9' '7' 'True' 'Bruno' '14' 'O' 'leão'
 '1.6' '4' '10' 'False' 'João' '14' 'M' 'escorpião' '1.58' '8' '9' 'True'
 'Jordana' '13' 'F' 'escorpião' '1.72' '9' '9' 'False']


In [183]:
# 12 - Desafio!

arr = ['Amélia', 13, 'F', 'peixes', 1.51, 9, 7, True, 'Bruno', 14, 'O', 'leão', 1.60, 4, 10, False, 'João', 14, 'M', 'escorpião', 1.58, 8, 9, True, 'Jordana', 13, 'F', 'escorpião', 1.72, 9, 9, False]

arr_12 = np.array(arr)

# Imprimindo indexes com informações do tipo string
print('Indexs de Strings no array')
for index, x in np.ndenumerate(arr_12):
    if not x[0].isnumeric():
        if x != 'True' and x != 'False':
            print(index, x)

print('-'*32)
# Separando as informações do objeto

arr_dividido = np.split(arr_12, 4)

arr_1 = arr_dividido[0]
arr_2 = arr_dividido[1]
arr_3 = arr_dividido[2]
arr_4 = arr_dividido[3]


print(f"Array do aluno: {arr_1[0]}")
print(arr_1)
print('-'*32)

print(f"Array do aluno: {arr_2[0]}")
print(arr_2)
print('-'*32)

print(f"Array do aluno: {arr_3[0]}")
print(arr_3)
print('-'*32)

print(f"Array do aluno: {arr_4[0]}")
print(arr_4)
print('-'*32)

  
    

Indexs de Strings no array
(0,) Amélia
(2,) F
(3,) peixes
(8,) Bruno
(10,) O
(11,) leão
(16,) João
(18,) M
(19,) escorpião
(24,) Jordana
(26,) F
(27,) escorpião
--------------------------------
Array do aluno: Amélia
['Amélia' '13' 'F' 'peixes' '1.51' '9' '7' 'True']
--------------------------------
Array do aluno: Bruno
['Bruno' '14' 'O' 'leão' '1.6' '4' '10' 'False']
--------------------------------
Array do aluno: João
['João' '14' 'M' 'escorpião' '1.58' '8' '9' 'True']
--------------------------------
Array do aluno: Jordana
['Jordana' '13' 'F' 'escorpião' '1.72' '9' '9' 'False']
--------------------------------


In [229]:
# Separar em duas colunas com nome, idade, genero e signo já a segunda, com altura, nota primeiro bimestre e nota segundo bimestre 
def retorna_Matriz(array):
    matriz = np.split(array, 2)
    x = matriz[0]
    y = matriz[1]
    matriz = np.column_stack((x,y)).reshape(4,2)
    return matriz

print(f"Matriz 4x2 do aluno: {arr_1[0]}")
print(retorna_Matriz(arr_1))
print('-'*32)

print(f"Matriz 4x2 do aluno: {arr_2[0]}")
print(retorna_Matriz(arr_2))
print('-'*32)

print(f"Matriz 4x2 do aluno: {arr_3[0]}")
print(retorna_Matriz(arr_3))
print('-'*32)

print(f"Matriz 4x2 do aluno: {arr_4[0]}")
print(retorna_Matriz(arr_4))
print('-'*32)


Matriz 4x2 do aluno: Amélia
[['Amélia' '1.51']
 ['13' '9']
 ['F' '7']
 ['peixes' 'True']]
--------------------------------
Matriz 4x2 do aluno: Bruno
[['Bruno' '1.6']
 ['14' '4']
 ['O' '10']
 ['leão' 'False']]
--------------------------------
Matriz 4x2 do aluno: João
[['João' '1.58']
 ['14' '8']
 ['M' '9']
 ['escorpião' 'True']]
--------------------------------
Matriz 4x2 do aluno: Jordana
[['Jordana' '1.72']
 ['13' '9']
 ['F' '9']
 ['escorpião' 'False']]
--------------------------------


In [265]:
# Eliminando gênero de alunos com idade inferior à 13 anos

def verifica_Idade(matriz):
    if int(matriz[1,0]) < 14:
        array_mod = np.delete(matriz,[4]) # Aparentemente, transforma minha matriz em array
        return array_mod
    else:
        return matriz.flatten()

mtx_1 = retorna_Matriz(arr_1)
mtx_2 = retorna_Matriz(arr_2)
mtx_3 = retorna_Matriz(arr_3)
mtx_4 = retorna_Matriz(arr_4)

# teste = verifica_Idade(mtx_1)
# print(teste)

print(f"Array do aluno: {arr_1[0]}")
print(verifica_Idade(mtx_1))
print('-'*32)

print(f"Array do aluno: {arr_2[0]}")
print(verifica_Idade(mtx_2))
print('-'*32)

print(f"Array do aluno: {arr_3[0]}")
print(verifica_Idade(mtx_3))
print('-'*32)

print(f"Array do aluno: {arr_4[0]}")
print(verifica_Idade(mtx_4))
print('-'*32)

Array do aluno: Amélia
['Amélia' '1.51' '13' '9' '7' 'peixes' 'True']
--------------------------------
Array do aluno: Bruno
['Bruno' '1.6' '14' '4' 'O' '10' 'leão' 'False']
--------------------------------
Array do aluno: João
['João' '1.58' '14' '8' 'M' '9' 'escorpião' 'True']
--------------------------------
Array do aluno: Jordana
['Jordana' '1.72' '13' '9' '9' 'escorpião' 'False']
--------------------------------
