In [2]:
# 1 - Testando Hipóteses
import numpy as np
arr = np.arange(50)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [4]:
arr_atualizado = arr[arr % 2]
print(arr_atualizado)

[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 0 1]


In [5]:
arr_atualizado = arr[arr > 5]
print(arr_atualizado)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29
 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [6]:
arr_atualizado = arr[arr <= 10]
print(arr_atualizado)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [16]:
arr_atualizado = arr[(arr != 1) | (arr != 3)]
print(arr_atualizado)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [62]:
# 2 Criar um array aleatório e máscaras

# Criando array aleatório de 15 itens
import numpy as np
from random import random
arr = np.random.randint(0, 100, 15)
# Verificando o Array
print(arr)



[24 68 80 19 23 76 40 33 72 27 48 21 40 34 78]


In [56]:
# Maior número do array
print("O maior número do array <max>:", arr.max())

O maior número do array <max>: 84


In [57]:
# Posição do maior número do array
# Utilizando argmax
print("A posição do maior número <argmax>: ", arr.argmax())


A posição do maior número <argmax>:  12


In [58]:
# Verificando quais números são maiores que 10
# Aplicação de máscaras

mascara_1 = arr[arr > 10]
print(mascara_1)

[21 24 49 20 21 21 25 25 84 67]


In [61]:
# Criando uma lista com os números entre 10 e 30

mascara_2 = arr[(arr > 10) & (arr < 30)]
mascara_2 = mascara_2.tolist()
print(mascara_2)

[21, 24, 20, 21, 21, 25, 25]


In [151]:
# 3 - Utilizando Matrizes! 

# Criando uma matriz (3,2) linearmente espaçada entre 0 e 100 com intervalos de 20

mat_1 = (np.linspace(0, 100, 6).astype(int)).reshape(3,2)

print('Matriz 1')
print(mat_1)
print('-'*21)

# Gerando uma matriz (5, 2) com números entre 0, 100

mat_2 = np.random.randint(0, 100, (5, 2))

print('Matriz 2')
print(mat_2)
print('-'*21)


# Criando um array com dimensões que quando multiplique a matriz do item a devolva a mesma (matriz identidade!)

mat_3 = np.identity(2, dtype = int)

print('Matriz 3')
print(mat_3)
print('-'*21)


matmul = np.matmul(mat_1, mat_3)

print('Matriz resultante <matmul>')
print(matmul)
print('-'*21)





Matriz 1
[[  0  20]
 [ 40  60]
 [ 80 100]]
---------------------
Matriz 2
[[32 12]
 [74 36]
 [25 29]
 [86 76]
 [62 98]]
---------------------
Matriz 3
[[1 0]
 [0 1]]
---------------------
Matriz resultante <matmul>
[[  0  20]
 [ 40  60]
 [ 80 100]]
---------------------
